# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

puts "**Creating Emotional Reactions**"
EmotionalReaction.create([
  {name: "Appreciated", description: "Made you feel appreciated"},
  {name: "Calm", description: "Made you feel calm"},
  {name: "Cheered Up", description: "Made you feel cheered up"},
  {name: "Creative", description: "Made you feel creative"},
  {name: "Energized", description: "Made you feel energized"},
  {name: "Excited", description: "Made you feel excited"},
  {name: "Grateful", description: "Made you feel grateful"},
  {name: "Happy", description: "Made you feel happy"},
  {name: "Inspired", description: "Made you feel inspired"},
  {name: "Intellectual", description: "Made you feel intellectual"},
  {name: "Joyful", description: "Made you feel joyful"},
  {name: "Laughing", description: "Made you laugh"},
  {name: "Listened To", description: "Made you feel listened to"},
  {name: "Loved", description: "Made you feel loved"},
  {name: "Motivated", description: "Made you feel motivated"},
  {name: "Optimistic", description: "Made you feel optimistic"},
  {name: "Problems Solved", description: "Made you feel like problems were solved"},
  {name: "Smart", description: "Made you feel smart"},
  {name: "Smiling", description: "Made you smile"},
  {name: "Special", description: "Made you feel special"},
  {name: "Trusting", description: "Made you feel trusting"},
  {name: "Valued", description: "Made you feel valued"},
  {name: "Like a Winner", description: "Made you feel like a winner"},
  
  {name: "Abandoned", description: "Made you feel abandoned"},
  {name: "Anxious", description: "Made you feel anxious"},
  {name: "Bitter", description: "Made you feel bitter"},
  {name: "Confused", description: "Made you feel confused"},
  {name: "Depressed", description: "Made you feel depressed"},
  {name: "Desperate", description: "Made you feel desperate"},
  {name: "Disappointed", description: "Made you feel disappointed"},
  {name: "Empty", description: "Made you feel empty"},
  {name: "Frustrated", description: "Made you feel frustrated"},
  {name: "Hopeless", description: "Made you feel hopeless"},
  {name: "Let Down", description: "Made you feel let down"},
  {name: "Like a Loser", description: "Made you feel like a loser"},
  {name: "Needy", description: "Made you feel needy"},
  {name: "Overwhelmed", description: "Made you feel overwhelmed"},
  {name: "Pessimistic", description: "Made you feel pessimistic"},
  {name: "Problems Created", description: "Made you feel like problems were created"},
  {name: "Sad", description: "Made you feel sad"},
  {name: "Scared", description: "Made you feel scared"},
  {name: "Smothered", description: "Made you feel smothered"},
  {name: "Stressed", description: "Made you feel stressed"},
  {name: "Tired", description: "Made you feel tired"},
  {name: "Used", description: "Made you feel used"}
])

puts "**Creating Interaction Categories**"
InteractionCategory.create([
	{name: "Social/Personal", description: "You both are happy to be in the other's company, or are trying! Not related to business."},
  {name: "Business/Career/Work", description: "You work together either at a job, as a vendor, in a business, etc. and have a measure of a relationship."},
  {name: "Transactional", description: "You or the other person is getting something transactional out of the meeting/contact, and it is really nothing more."}
])

puts "**Creating Countries**"
LastKnownCountry.create([
  {name: "Afghanistan"},
  {name: "Albania"},
  {name: "Algeria"},
  {name: "Andorra"},
  {name: "Angola"},
  {name: "Antigua & Barbuda"},
  {name: "Argentina"},
  {name: "Armenia"},
  {name: "Australia"},
  {name: "Austria"},
  {name: "Azerbaijan"},
  {name: "Bahamas"},
  {name: "Bahrain"},
  {name: "Bangladesh"},
  {name: "Barbados"},
  {name: "Belarus"},
  {name: "Belgium"},
  {name: "Belize"},
  {name: "Benin"},
  {name: "Bhutan"},
  {name: "Bolivia"},
  {name: "Bosnia & Herzegovina"},
  {name: "Botswana"},
  {name: "Brazil"},
  {name: "Brunei"},
  {name: "Bulgaria"},
  {name: "Burkina Faso"},
  {name: "Burundi"},
  {name: "Cambodia"},
  {name: "Cameroon"},
  {name: "Canada"},
  {name: "Cape Verde"},
  {name: "Central African Rep"},
  {name: "Chad"},
  {name: "Chile"},
  {name: "China"},
  {name: "Colombia"},
  {name: "Comoros"},
  {name: "Congo {Republic}"},
  {name: "Congo {Democratic Rep}"},
  {name: "Costa Rica"},
  {name: "Croatia"},
  {name: "Cuba"},
  {name: "Cyprus"},
  {name: "Czechia {Czech Republic}"},
  {name: "Denmark"},
  {name: "Djibouti"},
  {name: "Dominica"},
  {name: "Dominican Republic"},
  {name: "East Timor"},
  {name: "Ecuador"},
  {name: "Egypt"},
  {name: "El Salvador"},
  {name: "Equatorial Guinea"},
  {name: "Eritrea"},
  {name: "Estonia"},
  {name: "eSwatini {Swaziland}"},
  {name: "Ethiopia"},
  {name: "Fiji"},
  {name: "Finland"},
  {name: "France"},
  {name: "Gabon"},
  {name: "Gambia"},
  {name: "Georgia"},
  {name: "Germany"},
  {name: "Ghana"},
  {name: "Greece"},
  {name: "Greenland"},
  {name: "Grenada"},
  {name: "Guatemala"},
  {name: "Guinea"},
  {name: "Guinea-Bissau"},
  {name: "Guyana"},
  {name: "Haiti"},
  {name: "Honduras"},
  {name: "Hungary"},
  {name: "Iceland"},
  {name: "India"},
  {name: "Indonesia"},
  {name: "Iran"},
  {name: "Iraq"},
  {name: "Ireland {Republic}"},
  {name: "Israel"},
  {name: "Italy"},
  {name: "Ivory Coast"},
  {name: "Jamaica"},
  {name: "Japan"},
  {name: "Jordan"},
  {name: "Kazakhstan"},
  {name: "Kenya"},
  {name: "Kiribati"},
  {name: "Korea North"},
  {name: "Korea South"},
  {name: "Kosovo"},
  {name: "Kuwait"},
  {name: "Kyrgyzstan"},
  {name: "Laos"},
  {name: "Latvia"},
  {name: "Lebanon"},
  {name: "Lesotho"},
  {name: "Liberia"},
  {name: "Libya"},
  {name: "Liechtenstein"},
  {name: "Lithuania"},
  {name: "Luxembourg"},
  {name: "Macedonia"},
  {name: "Madagascar"},
  {name: "Malawi"},
  {name: "Malaysia"},
  {name: "Maldives"},
  {name: "Mali"},
  {name: "Malta"},
  {name: "Marshall Islands"},
  {name: "Mauritania"},
  {name: "Mauritius"},
  {name: "Mexico"},
  {name: "Micronesia"},
  {name: "Moldova"},
  {name: "Monaco"},
  {name: "Mongolia"},
  {name: "Montenegro"},
  {name: "Morocco"},
  {name: "Mozambique"},
  {name: "Myanmar {Burma}"},
  {name: "Namibia"},
  {name: "Nauru"},
  {name: "Nepal"},
  {name: "Netherlands"},
  {name: "New Zealand"},
  {name: "Nicaragua"},
  {name: "Niger"},
  {name: "Nigeria"},
  {name: "Norway"},
  {name: "Oman"},
  {name: "Pakistan"},
  {name: "Palau"},
  {name: "Palestine/Israel"},
  {name: "Panama"},
  {name: "Papua New Guinea"},
  {name: "Paraguay"},
  {name: "Peru"},
  {name: "Philippines"},
  {name: "Poland"},
  {name: "Portugal"},
  {name: "Qatar"},
  {name: "Romania"},
  {name: "Russia"},
  {name: "Rwanda"},
  {name: "Saint Kitts & Nevis"},
  {name: "Saint Lucia"},
  {name: "Saint Vincent & the Grenadines"},
  {name: "Samoa"},
  {name: "San Marino"},
  {name: "Sao Tome & Principe"},
  {name: "Saudi Arabia"},
  {name: "Senegal"},
  {name: "Serbia"},
  {name: "Seychelles"},
  {name: "Sierra Leone"},
  {name: "Singapore"},
  {name: "Slovakia"},
  {name: "Slovenia"},
  {name: "Solomon Islands"},
  {name: "Somalia"},
  {name: "South Africa"},
  {name: "South Sudan"},
  {name: "Spain"},
  {name: "Sri Lanka"},
  {name: "Sudan"},
  {name: "Suriname"},
  {name: "Sweden"},
  {name: "Switzerland"},
  {name: "Syria"},
  {name: "Taiwan"},
  {name: "Tajikistan"},
  {name: "Tanzania"},
  {name: "Thailand"},
  {name: "Togo"},
  {name: "Tonga"},
  {name: "Trinidad & Tobago"},
  {name: "Tunisia"},
  {name: "Turkey"},
  {name: "Turkmenistan"},
  {name: "Tuvalu"},
  {name: "Uganda"},
  {name: "Ukraine"},
  {name: "United Arab Emirates"},
  {name: "United Kingdom"},
  {name: "United States"},
  {name: "Uruguay"},
  {name: "Uzbekistan"},
  {name: "Vanuatu"},
  {name: "Vatican City"},
  {name: "Venezuela"},
  {name: "Vietnam"},
  {name: "Yemen"},
  {name: "Zambia"},
  {name: "Zimbabwe"}
])

